placeholders:
  presets:
    mindustry_name:
      steps:
        - text: "%player:name_colored%"
    mindustry_chat:
      steps:
        - text: "[coral][[%player:name_colored%[coral]]:[white] %argument:message%"
    mindustry_join:
      steps:
        - text: "[accent]%player:name_raw% has connected."
    mindustry_quit:
      steps:
        - text: "[accent]%player:name_raw% has disconnected."
